### ISSUE TITLE
Failure to grunt

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/color-vision#126]
```
color-vision : build : phet-io
Failure to grunt snapshot-1539967945494-phet-io/color-vision:
Running "lint-all" task

Running "clean" task

Running "build" task
Building runnable repository (color-vision, brands: phet, phet-io)
Building brand: phet
>> require.js optimization for brand: phet complete (4450263 bytes)
>> Minification for phet complete
>> Require.js: 1761229 bytes
>> Preloads: 238268 bytes
>> Mipmaps: 24286 bytes
Building brand: phet-io
Fatal error: Perennial task failed:
Error: Error: Error: Unable to read "/data/share/phet/continuous-testing/snapshot-1539967945494-phet-io/phet-io/js/types/BooleanIO.js" file (Error code: ENOENT).
In module tree:
    color-vision-main
      COLOR_VISION/rgb/RGBScreen
        COLOR_VISION/rgb/model/RGBModel
          COLOR_VISION/common/model/ColorVisionModel

  at /data/share/phet/continuous-testing/snapshot-1539967945494-phet-io/chipper/js/grunt/requireBuild.js:107:15
  at /data/share/phet/continuous-testing/snapshot-1539967945494-phet-io/chipper/node_modules/requirejs/bin/r.js:3059:39
  at /data/share/phet/continuous-testing/snapshot-1539967945494-phet-io/chipper/node_modules/requirejs/bin/r.js:2999:25
  at Function.prim.nextTick (/data/share/phet/continuous-testing/snapshot-1539967945494-phet-io/chipper/node_modules/requirejs/bin/r.js:28083:9)
  at Object.errback (/data/share/phet/continuous-testing/snapshot-1539967945494-phet-io/chipper/node_modules/requirejs/bin/r.js:2998:26)
  at Object.callback (/data/share/phet/continuous-testing/snapshot-1539967945494-phet-io/chipper/node_modules/requirejs/bin/r.js:2984:23)
  at Object.then (/data/share/phet/continuous-testing/snapshot-1539967945494-phet-io/chipper/node_modules/requirejs/bin/r.js:3038:23)
  at runBuild (/data/share/phet/continuous-testing/snapshot-1539967945494-phet-io/chipper/node_modules/requirejs/bin/r.js:30302:48)
  at Object.execCb (/data/share/phet/continuous-testing/snapshot-1539967945494-phet-io/chipper/node_modules/requirejs/bin/r.js:1946:33)
  at Module.check (/data/share/phet/continuous-testing/snapshot-1539967945494-phet-io/chipper/node_modules/requirejs/bin/r.js:1133:51)
  at Module.enable (/data/share/phet/continuous-testing/snapshot-1539967945494-phet-io/chipper/node_modules/requirejs/bin/r.js:1426:22)
  at Module.init (/data/share/phet/continuous-testing/snapshot-1539967945494-phet-io/chipper/node_modules/requirejs/bin/r.js:1038:26)
  at /data/share/phet/continuous-testing/snapshot-1539967945494-phet-io/chipper/node_modules/requirejs/bin/r.js:1710:36
  at _combinedTickCallback (internal/process/next_tick.js:132:7)
  at process._tickCallback (internal/process/next_tick.js:181:9)

Full Error details:
{}


Approximately 10/19/2018, 10:52:25 AM
```

**Comment by pixelzoom** [comment]
> Error: Error: Error: Unable to read "/data/share/phet/continuous-testing/snapshot-1539967945494-phet-io/phet-io/js/types/BooleanIO.js" file (Error code: ENOENT).

@zepumph This looks like it's related to https://github.com/phetsims/phet-io/issues/1396, moving the IO types.

**Comment by zepumph** [comment]
For some reason color vision wasn't pushed with everything else. It should be fixed now.
