### ISSUE TITLE
CT: should have type: SingleBulbPhotonIO in allTypes

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/color-vision#132]
Similar to https://github.com/phetsims/beers-law-lab/issues/244. This longstanding problem was apparently revealed when Studio started running on CT again recently.  The solution is to port dynamic SingleBulbPhoton to use PhetioGroup.

```
color-vision : phet-io-studio-fuzz : require.js : run
Uncaught Error: should have type: SingleBulbPhotonIO in allTypes. May need grunt update?
Error: should have type: SingleBulbPhotonIO in allTypes. May need grunt update?
    at window.assert (https://bayes.colorado.edu/continuous-testing/snapshot-1582032248597/phet-io-wrappers/common/js/assert.js:32:13)
    at getCreator (https://bayes.colorado.edu/continuous-testing/snapshot-1582032248597/studio/js/StudioInstanceCreator.js:778:15)
    at StudioInstanceCreator.createStudioInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1582032248597/studio/js/StudioInstanceCreator.js:61:26)
    at Studio.onPhetioElementAdded (https://bayes.colorado.edu/continuous-testing/snapshot-1582032248597/studio/js/Studio.js:276:63)
    at phetioElementAdded (https://bayes.colorado.edu/continuous-testing/snapshot-1582032248597/studio/js/main.js:50:26)
    at Client.dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1582032248597/phet-io-wrappers/common/js/Client.js:452:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1582032248597/phet-io-wrappers/common/js/Client.js:341:24)
id: Bayes Chrome
Approximately 2/18/2020, 6:24:08 AM
```

**Comment by pixelzoom** [comment]
Before working on this issue, verify that individual photons really need to be instrumented. Don't make the same mistake that was apparently made in https://github.com/phetsims/beers-law-lab/issues/244#issuecomment-598472966.
