### ISSUE TITLE
CT impossible set state from iterate

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/color-vision#135]
```
color-vision : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/phet-io-wrappers/state/?sim=color-vision&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22color-vision%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1601845816475%22%2C%22timestamp%22%3A1601887902100%7D
Uncaught Error: Assertion failed: Impossible set state from iterate; unset state:
{
"colorVision.singleBulbScreen.model.photonBeam.photons~1": {
"isWhite": false,
"color": {
"r": 0,
"g": 0,
"b": 0,
"a": 0
},
"passedFilter": false,
"position": {
"x": 280,
"y": 65
},
"velocity": {
"x": -240,
"y": 0
},
"intensity": 1
}
}
Error: Assertion failed: Impossible set state from iterate; unset state:
{
"colorVision.singleBulbScreen.model.photonBeam.photons~1": {
"isWhite": false,
"color": {
"r": 0,
"g": 0,
"b": 0,
"a": 0
},
"passedFilter": false,
"position": {
"x": 280,
"y": 65
},
"velocity": {
"x": -240,
"y": 0
},
"intensity": 1
}
}
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/assert/js/assert.js:22:13)
at PhetioStateEngine.iterate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/phet-io/js/PhetioStateEngine.js:346:19)
at PhetioStateEngine.setState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/phet-io/js/PhetioStateEngine.js:248:31)
at PhetioStateEngine.setFullState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/phet-io/js/PhetioStateEngine.js:267:10)
at PhetioEngine.implementation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/phet-io/js/phetioEngine.js:891:32)
at PhetioCommandProcessor.processCommand (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/phet-io/js/phetioCommandProcessor.js:286:51)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/phet-io/js/phetioCommandProcessor.js:172:36
at Array.map (<anonymous>)
at PhetioCommandProcessor.processCommands (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/phet-io/js/phetioCommandProcessor.js:170:30)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/phet-io/js/phetioCommandProcessor.js:109:16
id: Bayes Chrome
Snapshot from 10/4/2020, 3:10:16 PM

----------------------------------

color-vision : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/phet-io-wrappers/state/?sim=color-vision&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22color-vision%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1601845816475%22%2C%22timestamp%22%3A1601896317366%7D
Uncaught Error: Assertion failed: Impossible set state from iterate; unset state:
{
"colorVision.singleBulbScreen.model.photonBeam.photons~1": {
"isWhite": false,
"color": {
"r": 0,
"g": 0,
"b": 0,
"a": 0
},
"passedFilter": false,
"position": {
"x": 255.28,
"y": 65
},
"velocity": {
"x": -240,
"y": 0
},
"intensity": 1
},
"colorVision.singleBulbScreen.model.photonBeam.photons~2": {
"isWhite": false,
"color": {
"r": 0,
"g": 0,
"b": 0,
"a": 0
},
"passedFilter": false,
"position": {
"x": 266.08,
"y": 65
},
"velocity": {
"x": -240,
"y": 0
},
"intensity": 1
},
"colorVision.singleBulbScreen.model.photonBeam.photons~3": {
"isWhite": false,
"color": {
"r": 0,
"g": 0,
"b": 0,
"a": 0
},
"passedFilter": false,
"position": {
"x": 280,
"y": 65
},
"velocity": {
"x": -240,
"y": 0
},
"intensity": 1
}
}
Error: Assertion failed: Impossible set state from iterate; unset state:
{
"colorVision.singleBulbScreen.model.photonBeam.photons~1": {
"isWhite": false,
"color": {
"r": 0,
"g": 0,
"b": 0,
"a": 0
},
"passedFilter": false,
"position": {
"x": 255.28,
"y": 65
},
"velocity": {
"x": -240,
"y": 0
},
"intensity": 1
},
"colorVision.singleBulbScreen.model.photonBeam.photons~2": {
"isWhite": false,
"color": {
"r": 0,
"g": 0,
"b": 0,
"a": 0
},
"passedFilter": false,
"position": {
"x": 266.08,
"y": 65
},
"velocity": {
"x": -240,
"y": 0
},
"intensity": 1
},
"colorVision.singleBulbScreen.model.photonBeam.photons~3": {
"isWhite": false,
"color": {
"r": 0,
"g": 0,
"b": 0,
"a": 0
},
"passedFilter": false,
"position": {
"x": 280,
"y": 65
},
"velocity": {
"x": -240,
"y": 0
},
"intensity": 1
}
}
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/assert/js/assert.js:22:13)
at PhetioStateEngine.iterate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/phet-io/js/PhetioStateEngine.js:346:19)
at PhetioStateEngine.setState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/phet-io/js/PhetioStateEngine.js:248:31)
at PhetioStateEngine.setFullState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/phet-io/js/PhetioStateEngine.js:267:10)
at PhetioEngine.implementation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/phet-io/js/phetioEngine.js:891:32)
at PhetioCommandProcessor.processCommand (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/phet-io/js/phetioCommandProcessor.js:286:51)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/phet-io/js/phetioCommandProcessor.js:172:36
at Array.map (<anonymous>)
at PhetioCommandProcessor.processCommands (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/phet-io/js/phetioCommandProcessor.js:170:30)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/phet-io/js/phetioCommandProcessor.js:109:16
id: Bayes Chrome
Snapshot from 10/4/2020, 3:10:16 PM

----------------------------------

color-vision : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/phet-io-wrappers/state/?sim=color-vision&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22color-vision%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1601845816475%22%2C%22timestamp%22%3A1601902993494%7D
Uncaught Error: Assertion failed: Impossible set state from iterate; unset state:
{
"colorVision.singleBulbScreen.model.photonBeam.photons~0": {
"isWhite": false,
"color": {
"r": 0,
"g": 0,
"b": 0,
"a": 0
},
"passedFilter": false,
"position": {
"x": 0,
"y": 65
},
"velocity": {
"x": -240,
"y": 0
},
"intensity": 1
},
"colorVision.singleBulbScreen.model.photonBeam.photons~1": {
"isWhite": false,
"color": {
"r": 0,
"g": 0,
"b": 0,
"a": 0
},
"passedFilter": false,
"position": {
"x": 0,
"y": 65
},
"velocity": {
"x": -240,
"y": 0
},
"intensity": 1
}
}
Error: Assertion failed: Impossible set state from iterate; unset state:
{
"colorVision.singleBulbScreen.model.photonBeam.photons~0": {
"isWhite": false,
"color": {
"r": 0,
"g": 0,
"b": 0,
"a": 0
},
"passedFilter": false,
"position": {
"x": 0,
"y": 65
},
"velocity": {
"x": -240,
"y": 0
},
"intensity": 1
},
"colorVision.singleBulbScreen.model.photonBeam.photons~1": {
"isWhite": false,
"color": {
"r": 0,
"g": 0,
"b": 0,
"a": 0
},
"passedFilter": false,
"position": {
"x": 0,
"y": 65
},
"velocity": {
"x": -240,
"y": 0
},
"intensity": 1
}
}
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/assert/js/assert.js:22:13)
at PhetioStateEngine.iterate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/phet-io/js/PhetioStateEngine.js:346:19)
at PhetioStateEngine.setState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/phet-io/js/PhetioStateEngine.js:248:31)
at PhetioStateEngine.setFullState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/phet-io/js/PhetioStateEngine.js:267:10)
at PhetioEngine.implementation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/phet-io/js/phetioEngine.js:891:32)
at PhetioCommandProcessor.processCommand (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/phet-io/js/phetioCommandProcessor.js:286:51)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/phet-io/js/phetioCommandProcessor.js:172:36
at Array.map (<anonymous>)
at PhetioCommandProcessor.processCommands (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/phet-io/js/phetioCommandProcessor.js:170:30)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601845816475/phet-io/js/phetioCommandProcessor.js:109:16
id: Bayes Chrome
Snapshot from 10/4/2020, 3:10:16 PM
```

**Comment by samreid** [comment]
I uninstrumented SingleBulbPhoton and its group.  We can reinstrument it using PhetioGroup in the future, if necessary.  But we may equally likely choose that the photons are transient.  The main argument I see for instrumenting the photons is if we want to be able to create static "images" of the sim with photons already created.  We will decide that when we revisit this sim for PhET-iO.
